load_data:
  folder_names: 
    - adj_data_list_augmented_benchmark_10machines
  #  - adj_data_list_diff_prediction_instances
  path: /workspaces/gnn_scheduler/data
  seed: 0
  eval_size: 0.1
  test_size: 0.2
model:
  conv_dim:
  - [64, 32]   # graph_conv_dim
  - 128        # aux_dim
  - [128, 1]   # linear_dim
  m_dim: 12       # Dimension of the molecular/node feature vector
  b_dim: 2        # Number of edge types/bond types
  dropout_rate: 0.  # Dropout rate for convolution layers
training:
  n_epochs: 10000
  optimizer: 'adam'
  learning_rate: 0.0001
  batch_size: 32
  weight_decay: 0.0001
  shuffle: true
  show_progress: false
